services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresPass
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-db-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'teste@teste.com'
      PGADMIN_DEFAULT_PASSWORD: 'teste'
    ports:
      - 16543:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - postgres-db-network
  elasticsearch:
    image: elasticsearch:7.17.0
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      discovery.type: 'single-node'
      ES_JAVA_OPTS: '-Xms3g -Xmx3g'
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - postgres-db-network

  kibana:
    image: kibana:7.17.0
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - postgres-db-network

volumes:
  postgres-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  esdata:
    driver: local
networks:
  postgres-db-network:
    driver: bridge
